/* automatically generated by rust-bindgen */

#![allow(dead_code,
         non_camel_case_types,
         non_upper_case_globals,
         non_snake_case)]
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct EFXEAXREVERBPROPERTIES {
    pub flDensity: f32,
    pub flDiffusion: f32,
    pub flGain: f32,
    pub flGainHF: f32,
    pub flGainLF: f32,
    pub flDecayTime: f32,
    pub flDecayHFRatio: f32,
    pub flDecayLFRatio: f32,
    pub flReflectionsGain: f32,
    pub flReflectionsDelay: f32,
    pub flReflectionsPan: [f32; 3usize],
    pub flLateReverbGain: f32,
    pub flLateReverbDelay: f32,
    pub flLateReverbPan: [f32; 3usize],
    pub flEchoTime: f32,
    pub flEchoDepth: f32,
    pub flModulationTime: f32,
    pub flModulationDepth: f32,
    pub flAirAbsorptionGainHF: f32,
    pub flHFReference: f32,
    pub flLFReference: f32,
    pub flRoomRolloffFactor: f32,
    pub iDecayHFLimit: ::std::os::raw::c_int,
}
impl ::std::default::Default for EFXEAXREVERBPROPERTIES {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type LPEFXEAXREVERBPROPERTIES = *mut EFXEAXREVERBPROPERTIES;
