/* automatically generated by rust-bindgen */

#![allow(dead_code,
         non_camel_case_types,
         non_upper_case_globals,
         non_snake_case)]

use ffi::*;

pub const _STDINT_H: ::std::os::raw::c_int = 1;
pub const INT8_MIN: ::std::os::raw::c_int = -128;
pub const INT16_MIN: ::std::os::raw::c_int = -32768;
pub const INT32_MIN: ::std::os::raw::c_int = -2147483648;
pub const INT8_MAX: ::std::os::raw::c_int = 127;
pub const INT16_MAX: ::std::os::raw::c_int = 32767;
pub const INT32_MAX: ::std::os::raw::c_uint = 2147483647;
pub const UINT8_MAX: ::std::os::raw::c_int = 255;
pub const UINT16_MAX: ::std::os::raw::c_int = 65535;
pub const UINT32_MAX: ::std::os::raw::c_uint = 4294967295;
pub const INT_LEAST8_MIN: ::std::os::raw::c_int = -128;
pub const INT_LEAST16_MIN: ::std::os::raw::c_int = -32768;
pub const INT_LEAST32_MIN: ::std::os::raw::c_int = -2147483648;
pub const INT_LEAST8_MAX: ::std::os::raw::c_int = 127;
pub const INT_LEAST16_MAX: ::std::os::raw::c_int = 32767;
pub const INT_LEAST32_MAX: ::std::os::raw::c_uint = 2147483647;
pub const UINT_LEAST8_MAX: ::std::os::raw::c_int = 255;
pub const UINT_LEAST16_MAX: ::std::os::raw::c_int = 65535;
pub const UINT_LEAST32_MAX: ::std::os::raw::c_uint = 4294967295;
pub const INT_FAST8_MIN: ::std::os::raw::c_int = -128;
pub const INT_FAST16_MIN: ::std::os::raw::c_longlong = -9223372036854775808;
pub const INT_FAST32_MIN: ::std::os::raw::c_longlong = -9223372036854775808;
pub const INT_FAST8_MAX: ::std::os::raw::c_int = 127;
pub const INT_FAST16_MAX: ::std::os::raw::c_ulonglong = 9223372036854775807;
pub const INT_FAST32_MAX: ::std::os::raw::c_ulonglong = 9223372036854775807;
pub const UINT_FAST8_MAX: ::std::os::raw::c_int = 255;
pub const UINT_FAST16_MAX: ::std::os::raw::c_int = -1;
pub const UINT_FAST32_MAX: ::std::os::raw::c_int = -1;
pub const INTPTR_MIN: ::std::os::raw::c_longlong = -9223372036854775808;
pub const INTPTR_MAX: ::std::os::raw::c_ulonglong = 9223372036854775807;
pub const UINTPTR_MAX: ::std::os::raw::c_int = -1;
pub const PTRDIFF_MIN: ::std::os::raw::c_longlong = -9223372036854775808;
pub const PTRDIFF_MAX: ::std::os::raw::c_ulonglong = 9223372036854775807;
pub const SIG_ATOMIC_MIN: ::std::os::raw::c_int = -2147483648;
pub const SIG_ATOMIC_MAX: ::std::os::raw::c_uint = 2147483647;
pub const SIZE_MAX: ::std::os::raw::c_int = -1;
pub const WINT_MIN: ::std::os::raw::c_int = 0;
pub const WINT_MAX: ::std::os::raw::c_uint = 4294967295;
pub const AL_LOKI_IMA_ADPCM_format: ::std::os::raw::c_int = 1;
pub const AL_FORMAT_IMA_ADPCM_MONO16_EXT: ::std::os::raw::c_uint = 65536;
pub const AL_FORMAT_IMA_ADPCM_STEREO16_EXT: ::std::os::raw::c_uint = 65537;
pub const AL_LOKI_WAVE_format: ::std::os::raw::c_int = 1;
pub const AL_FORMAT_WAVE_EXT: ::std::os::raw::c_uint = 65538;
pub const AL_EXT_vorbis: ::std::os::raw::c_int = 1;
pub const AL_FORMAT_VORBIS_EXT: ::std::os::raw::c_uint = 65539;
pub const AL_LOKI_quadriphonic: ::std::os::raw::c_int = 1;
pub const AL_FORMAT_QUAD8_LOKI: ::std::os::raw::c_uint = 65540;
pub const AL_FORMAT_QUAD16_LOKI: ::std::os::raw::c_uint = 65541;
pub const AL_EXT_float32: ::std::os::raw::c_int = 1;
pub const AL_FORMAT_MONO_FLOAT32: ::std::os::raw::c_uint = 65552;
pub const AL_FORMAT_STEREO_FLOAT32: ::std::os::raw::c_uint = 65553;
pub const AL_EXT_double: ::std::os::raw::c_int = 1;
pub const AL_FORMAT_MONO_DOUBLE_EXT: ::std::os::raw::c_uint = 65554;
pub const AL_FORMAT_STEREO_DOUBLE_EXT: ::std::os::raw::c_uint = 65555;
pub const AL_EXT_MULAW: ::std::os::raw::c_int = 1;
pub const AL_FORMAT_MONO_MULAW_EXT: ::std::os::raw::c_uint = 65556;
pub const AL_FORMAT_STEREO_MULAW_EXT: ::std::os::raw::c_uint = 65557;
pub const AL_EXT_ALAW: ::std::os::raw::c_int = 1;
pub const AL_FORMAT_MONO_ALAW_EXT: ::std::os::raw::c_uint = 65558;
pub const AL_FORMAT_STEREO_ALAW_EXT: ::std::os::raw::c_uint = 65559;
pub const ALC_LOKI_audio_channel: ::std::os::raw::c_int = 1;
pub const ALC_CHAN_MAIN_LOKI: ::std::os::raw::c_uint = 5242881;
pub const ALC_CHAN_PCM_LOKI: ::std::os::raw::c_uint = 5242882;
pub const ALC_CHAN_CD_LOKI: ::std::os::raw::c_uint = 5242883;
pub const AL_EXT_MCFORMATS: ::std::os::raw::c_int = 1;
pub const AL_FORMAT_QUAD8: ::std::os::raw::c_int = 4612;
pub const AL_FORMAT_QUAD16: ::std::os::raw::c_int = 4613;
pub const AL_FORMAT_QUAD32: ::std::os::raw::c_int = 4614;
pub const AL_FORMAT_REAR8: ::std::os::raw::c_int = 4615;
pub const AL_FORMAT_REAR16: ::std::os::raw::c_int = 4616;
pub const AL_FORMAT_REAR32: ::std::os::raw::c_int = 4617;
pub const AL_FORMAT_51CHN8: ::std::os::raw::c_int = 4618;
pub const AL_FORMAT_51CHN16: ::std::os::raw::c_int = 4619;
pub const AL_FORMAT_51CHN32: ::std::os::raw::c_int = 4620;
pub const AL_FORMAT_61CHN8: ::std::os::raw::c_int = 4621;
pub const AL_FORMAT_61CHN16: ::std::os::raw::c_int = 4622;
pub const AL_FORMAT_61CHN32: ::std::os::raw::c_int = 4623;
pub const AL_FORMAT_71CHN8: ::std::os::raw::c_int = 4624;
pub const AL_FORMAT_71CHN16: ::std::os::raw::c_int = 4625;
pub const AL_FORMAT_71CHN32: ::std::os::raw::c_int = 4626;
pub const AL_EXT_MULAW_MCFORMATS: ::std::os::raw::c_int = 1;
pub const AL_FORMAT_MONO_MULAW: ::std::os::raw::c_uint = 65556;
pub const AL_FORMAT_STEREO_MULAW: ::std::os::raw::c_uint = 65557;
pub const AL_FORMAT_QUAD_MULAW: ::std::os::raw::c_uint = 65569;
pub const AL_FORMAT_REAR_MULAW: ::std::os::raw::c_uint = 65570;
pub const AL_FORMAT_51CHN_MULAW: ::std::os::raw::c_uint = 65571;
pub const AL_FORMAT_61CHN_MULAW: ::std::os::raw::c_uint = 65572;
pub const AL_FORMAT_71CHN_MULAW: ::std::os::raw::c_uint = 65573;
pub const AL_EXT_IMA4: ::std::os::raw::c_int = 1;
pub const AL_FORMAT_MONO_IMA4: ::std::os::raw::c_int = 4864;
pub const AL_FORMAT_STEREO_IMA4: ::std::os::raw::c_int = 4865;
pub const AL_EXT_STATIC_BUFFER: ::std::os::raw::c_int = 1;
pub const ALC_EXT_EFX: ::std::os::raw::c_int = 1;
pub const ALC_EFX_MAJOR_VERSION: ::std::os::raw::c_uint = 131073;
pub const ALC_EFX_MINOR_VERSION: ::std::os::raw::c_uint = 131074;
pub const ALC_MAX_AUXILIARY_SENDS: ::std::os::raw::c_uint = 131075;
pub const AL_METERS_PER_UNIT: ::std::os::raw::c_uint = 131076;
pub const AL_DIRECT_FILTER: ::std::os::raw::c_uint = 131077;
pub const AL_AUXILIARY_SEND_FILTER: ::std::os::raw::c_uint = 131078;
pub const AL_AIR_ABSORPTION_FACTOR: ::std::os::raw::c_uint = 131079;
pub const AL_ROOM_ROLLOFF_FACTOR: ::std::os::raw::c_uint = 131080;
pub const AL_CONE_OUTER_GAINHF: ::std::os::raw::c_uint = 131081;
pub const AL_DIRECT_FILTER_GAINHF_AUTO: ::std::os::raw::c_uint = 131082;
pub const AL_AUXILIARY_SEND_FILTER_GAIN_AUTO: ::std::os::raw::c_uint = 131083;
pub const AL_AUXILIARY_SEND_FILTER_GAINHF_AUTO: ::std::os::raw::c_uint =
    131084;
pub const AL_REVERB_DENSITY: ::std::os::raw::c_int = 1;
pub const AL_REVERB_DIFFUSION: ::std::os::raw::c_int = 2;
pub const AL_REVERB_GAIN: ::std::os::raw::c_int = 3;
pub const AL_REVERB_GAINHF: ::std::os::raw::c_int = 4;
pub const AL_REVERB_DECAY_TIME: ::std::os::raw::c_int = 5;
pub const AL_REVERB_DECAY_HFRATIO: ::std::os::raw::c_int = 6;
pub const AL_REVERB_REFLECTIONS_GAIN: ::std::os::raw::c_int = 7;
pub const AL_REVERB_REFLECTIONS_DELAY: ::std::os::raw::c_int = 8;
pub const AL_REVERB_LATE_REVERB_GAIN: ::std::os::raw::c_int = 9;
pub const AL_REVERB_LATE_REVERB_DELAY: ::std::os::raw::c_int = 10;
pub const AL_REVERB_AIR_ABSORPTION_GAINHF: ::std::os::raw::c_int = 11;
pub const AL_REVERB_ROOM_ROLLOFF_FACTOR: ::std::os::raw::c_int = 12;
pub const AL_REVERB_DECAY_HFLIMIT: ::std::os::raw::c_int = 13;
pub const AL_EAXREVERB_DENSITY: ::std::os::raw::c_int = 1;
pub const AL_EAXREVERB_DIFFUSION: ::std::os::raw::c_int = 2;
pub const AL_EAXREVERB_GAIN: ::std::os::raw::c_int = 3;
pub const AL_EAXREVERB_GAINHF: ::std::os::raw::c_int = 4;
pub const AL_EAXREVERB_GAINLF: ::std::os::raw::c_int = 5;
pub const AL_EAXREVERB_DECAY_TIME: ::std::os::raw::c_int = 6;
pub const AL_EAXREVERB_DECAY_HFRATIO: ::std::os::raw::c_int = 7;
pub const AL_EAXREVERB_DECAY_LFRATIO: ::std::os::raw::c_int = 8;
pub const AL_EAXREVERB_REFLECTIONS_GAIN: ::std::os::raw::c_int = 9;
pub const AL_EAXREVERB_REFLECTIONS_DELAY: ::std::os::raw::c_int = 10;
pub const AL_EAXREVERB_REFLECTIONS_PAN: ::std::os::raw::c_int = 11;
pub const AL_EAXREVERB_LATE_REVERB_GAIN: ::std::os::raw::c_int = 12;
pub const AL_EAXREVERB_LATE_REVERB_DELAY: ::std::os::raw::c_int = 13;
pub const AL_EAXREVERB_LATE_REVERB_PAN: ::std::os::raw::c_int = 14;
pub const AL_EAXREVERB_ECHO_TIME: ::std::os::raw::c_int = 15;
pub const AL_EAXREVERB_ECHO_DEPTH: ::std::os::raw::c_int = 16;
pub const AL_EAXREVERB_MODULATION_TIME: ::std::os::raw::c_int = 17;
pub const AL_EAXREVERB_MODULATION_DEPTH: ::std::os::raw::c_int = 18;
pub const AL_EAXREVERB_AIR_ABSORPTION_GAINHF: ::std::os::raw::c_int = 19;
pub const AL_EAXREVERB_HFREFERENCE: ::std::os::raw::c_int = 20;
pub const AL_EAXREVERB_LFREFERENCE: ::std::os::raw::c_int = 21;
pub const AL_EAXREVERB_ROOM_ROLLOFF_FACTOR: ::std::os::raw::c_int = 22;
pub const AL_EAXREVERB_DECAY_HFLIMIT: ::std::os::raw::c_int = 23;
pub const AL_CHORUS_WAVEFORM: ::std::os::raw::c_int = 1;
pub const AL_CHORUS_PHASE: ::std::os::raw::c_int = 2;
pub const AL_CHORUS_RATE: ::std::os::raw::c_int = 3;
pub const AL_CHORUS_DEPTH: ::std::os::raw::c_int = 4;
pub const AL_CHORUS_FEEDBACK: ::std::os::raw::c_int = 5;
pub const AL_CHORUS_DELAY: ::std::os::raw::c_int = 6;
pub const AL_DISTORTION_EDGE: ::std::os::raw::c_int = 1;
pub const AL_DISTORTION_GAIN: ::std::os::raw::c_int = 2;
pub const AL_DISTORTION_LOWPASS_CUTOFF: ::std::os::raw::c_int = 3;
pub const AL_DISTORTION_EQCENTER: ::std::os::raw::c_int = 4;
pub const AL_DISTORTION_EQBANDWIDTH: ::std::os::raw::c_int = 5;
pub const AL_ECHO_DELAY: ::std::os::raw::c_int = 1;
pub const AL_ECHO_LRDELAY: ::std::os::raw::c_int = 2;
pub const AL_ECHO_DAMPING: ::std::os::raw::c_int = 3;
pub const AL_ECHO_FEEDBACK: ::std::os::raw::c_int = 4;
pub const AL_ECHO_SPREAD: ::std::os::raw::c_int = 5;
pub const AL_FLANGER_WAVEFORM: ::std::os::raw::c_int = 1;
pub const AL_FLANGER_PHASE: ::std::os::raw::c_int = 2;
pub const AL_FLANGER_RATE: ::std::os::raw::c_int = 3;
pub const AL_FLANGER_DEPTH: ::std::os::raw::c_int = 4;
pub const AL_FLANGER_FEEDBACK: ::std::os::raw::c_int = 5;
pub const AL_FLANGER_DELAY: ::std::os::raw::c_int = 6;
pub const AL_FREQUENCY_SHIFTER_FREQUENCY: ::std::os::raw::c_int = 1;
pub const AL_FREQUENCY_SHIFTER_LEFT_DIRECTION: ::std::os::raw::c_int = 2;
pub const AL_FREQUENCY_SHIFTER_RIGHT_DIRECTION: ::std::os::raw::c_int = 3;
pub const AL_VOCAL_MORPHER_PHONEMEA: ::std::os::raw::c_int = 1;
pub const AL_VOCAL_MORPHER_PHONEMEA_COARSE_TUNING: ::std::os::raw::c_int = 2;
pub const AL_VOCAL_MORPHER_PHONEMEB: ::std::os::raw::c_int = 3;
pub const AL_VOCAL_MORPHER_PHONEMEB_COARSE_TUNING: ::std::os::raw::c_int = 4;
pub const AL_VOCAL_MORPHER_WAVEFORM: ::std::os::raw::c_int = 5;
pub const AL_VOCAL_MORPHER_RATE: ::std::os::raw::c_int = 6;
pub const AL_PITCH_SHIFTER_COARSE_TUNE: ::std::os::raw::c_int = 1;
pub const AL_PITCH_SHIFTER_FINE_TUNE: ::std::os::raw::c_int = 2;
pub const AL_RING_MODULATOR_FREQUENCY: ::std::os::raw::c_int = 1;
pub const AL_RING_MODULATOR_HIGHPASS_CUTOFF: ::std::os::raw::c_int = 2;
pub const AL_RING_MODULATOR_WAVEFORM: ::std::os::raw::c_int = 3;
pub const AL_AUTOWAH_ATTACK_TIME: ::std::os::raw::c_int = 1;
pub const AL_AUTOWAH_RELEASE_TIME: ::std::os::raw::c_int = 2;
pub const AL_AUTOWAH_RESONANCE: ::std::os::raw::c_int = 3;
pub const AL_AUTOWAH_PEAK_GAIN: ::std::os::raw::c_int = 4;
pub const AL_COMPRESSOR_ONOFF: ::std::os::raw::c_int = 1;
pub const AL_EQUALIZER_LOW_GAIN: ::std::os::raw::c_int = 1;
pub const AL_EQUALIZER_LOW_CUTOFF: ::std::os::raw::c_int = 2;
pub const AL_EQUALIZER_MID1_GAIN: ::std::os::raw::c_int = 3;
pub const AL_EQUALIZER_MID1_CENTER: ::std::os::raw::c_int = 4;
pub const AL_EQUALIZER_MID1_WIDTH: ::std::os::raw::c_int = 5;
pub const AL_EQUALIZER_MID2_GAIN: ::std::os::raw::c_int = 6;
pub const AL_EQUALIZER_MID2_CENTER: ::std::os::raw::c_int = 7;
pub const AL_EQUALIZER_MID2_WIDTH: ::std::os::raw::c_int = 8;
pub const AL_EQUALIZER_HIGH_GAIN: ::std::os::raw::c_int = 9;
pub const AL_EQUALIZER_HIGH_CUTOFF: ::std::os::raw::c_int = 10;
pub const AL_EFFECT_FIRST_PARAMETER: ::std::os::raw::c_int = 0;
pub const AL_EFFECT_LAST_PARAMETER: ::std::os::raw::c_int = 32768;
pub const AL_EFFECT_TYPE: ::std::os::raw::c_int = 32769;
pub const AL_EFFECT_NULL: ::std::os::raw::c_int = 0;
pub const AL_EFFECT_REVERB: ::std::os::raw::c_int = 1;
pub const AL_EFFECT_CHORUS: ::std::os::raw::c_int = 2;
pub const AL_EFFECT_DISTORTION: ::std::os::raw::c_int = 3;
pub const AL_EFFECT_ECHO: ::std::os::raw::c_int = 4;
pub const AL_EFFECT_FLANGER: ::std::os::raw::c_int = 5;
pub const AL_EFFECT_FREQUENCY_SHIFTER: ::std::os::raw::c_int = 6;
pub const AL_EFFECT_VOCAL_MORPHER: ::std::os::raw::c_int = 7;
pub const AL_EFFECT_PITCH_SHIFTER: ::std::os::raw::c_int = 8;
pub const AL_EFFECT_RING_MODULATOR: ::std::os::raw::c_int = 9;
pub const AL_EFFECT_AUTOWAH: ::std::os::raw::c_int = 10;
pub const AL_EFFECT_COMPRESSOR: ::std::os::raw::c_int = 11;
pub const AL_EFFECT_EQUALIZER: ::std::os::raw::c_int = 12;
pub const AL_EFFECT_EAXREVERB: ::std::os::raw::c_int = 32768;
pub const AL_EFFECTSLOT_EFFECT: ::std::os::raw::c_int = 1;
pub const AL_EFFECTSLOT_GAIN: ::std::os::raw::c_int = 2;
pub const AL_EFFECTSLOT_AUXILIARY_SEND_AUTO: ::std::os::raw::c_int = 3;
pub const AL_EFFECTSLOT_NULL: ::std::os::raw::c_int = 0;
pub const AL_LOWPASS_GAIN: ::std::os::raw::c_int = 1;
pub const AL_LOWPASS_GAINHF: ::std::os::raw::c_int = 2;
pub const AL_HIGHPASS_GAIN: ::std::os::raw::c_int = 1;
pub const AL_HIGHPASS_GAINLF: ::std::os::raw::c_int = 2;
pub const AL_BANDPASS_GAIN: ::std::os::raw::c_int = 1;
pub const AL_BANDPASS_GAINLF: ::std::os::raw::c_int = 2;
pub const AL_BANDPASS_GAINHF: ::std::os::raw::c_int = 3;
pub const AL_FILTER_FIRST_PARAMETER: ::std::os::raw::c_int = 0;
pub const AL_FILTER_LAST_PARAMETER: ::std::os::raw::c_int = 32768;
pub const AL_FILTER_TYPE: ::std::os::raw::c_int = 32769;
pub const AL_FILTER_NULL: ::std::os::raw::c_int = 0;
pub const AL_FILTER_LOWPASS: ::std::os::raw::c_int = 1;
pub const AL_FILTER_HIGHPASS: ::std::os::raw::c_int = 2;
pub const AL_FILTER_BANDPASS: ::std::os::raw::c_int = 3;
pub const AL_CHORUS_WAVEFORM_SINUSOID: ::std::os::raw::c_int = 0;
pub const AL_CHORUS_WAVEFORM_TRIANGLE: ::std::os::raw::c_int = 1;
pub const AL_CHORUS_MIN_WAVEFORM: ::std::os::raw::c_int = 0;
pub const AL_CHORUS_MAX_WAVEFORM: ::std::os::raw::c_int = 1;
pub const AL_CHORUS_DEFAULT_WAVEFORM: ::std::os::raw::c_int = 1;
pub const AL_CHORUS_MIN_PHASE: ::std::os::raw::c_int = -180;
pub const AL_CHORUS_MAX_PHASE: ::std::os::raw::c_int = 180;
pub const AL_CHORUS_DEFAULT_PHASE: ::std::os::raw::c_int = 90;
pub const AL_FLANGER_WAVEFORM_SINUSOID: ::std::os::raw::c_int = 0;
pub const AL_FLANGER_WAVEFORM_TRIANGLE: ::std::os::raw::c_int = 1;
pub const AL_FLANGER_MIN_WAVEFORM: ::std::os::raw::c_int = 0;
pub const AL_FLANGER_MAX_WAVEFORM: ::std::os::raw::c_int = 1;
pub const AL_FLANGER_DEFAULT_WAVEFORM: ::std::os::raw::c_int = 1;
pub const AL_FLANGER_MIN_PHASE: ::std::os::raw::c_int = -180;
pub const AL_FLANGER_MAX_PHASE: ::std::os::raw::c_int = 180;
pub const AL_FLANGER_DEFAULT_PHASE: ::std::os::raw::c_int = 0;
pub const AL_FREQUENCY_SHIFTER_MIN_LEFT_DIRECTION: ::std::os::raw::c_int = 0;
pub const AL_FREQUENCY_SHIFTER_MAX_LEFT_DIRECTION: ::std::os::raw::c_int = 2;
pub const AL_FREQUENCY_SHIFTER_DEFAULT_LEFT_DIRECTION: ::std::os::raw::c_int =
    0;
pub const AL_FREQUENCY_SHIFTER_DIRECTION_DOWN: ::std::os::raw::c_int = 0;
pub const AL_FREQUENCY_SHIFTER_DIRECTION_UP: ::std::os::raw::c_int = 1;
pub const AL_FREQUENCY_SHIFTER_DIRECTION_OFF: ::std::os::raw::c_int = 2;
pub const AL_FREQUENCY_SHIFTER_MIN_RIGHT_DIRECTION: ::std::os::raw::c_int = 0;
pub const AL_FREQUENCY_SHIFTER_MAX_RIGHT_DIRECTION: ::std::os::raw::c_int = 2;
pub const AL_FREQUENCY_SHIFTER_DEFAULT_RIGHT_DIRECTION: ::std::os::raw::c_int
          =
    0;
pub const AL_VOCAL_MORPHER_MIN_PHONEMEA: ::std::os::raw::c_int = 0;
pub const AL_VOCAL_MORPHER_MAX_PHONEMEA: ::std::os::raw::c_int = 29;
pub const AL_VOCAL_MORPHER_DEFAULT_PHONEMEA: ::std::os::raw::c_int = 0;
pub const AL_VOCAL_MORPHER_MIN_PHONEMEA_COARSE_TUNING: ::std::os::raw::c_int =
    -24;
pub const AL_VOCAL_MORPHER_MAX_PHONEMEA_COARSE_TUNING: ::std::os::raw::c_int =
    24;
pub const AL_VOCAL_MORPHER_DEFAULT_PHONEMEA_COARSE_TUNING:
          ::std::os::raw::c_int =
    0;
pub const AL_VOCAL_MORPHER_MIN_PHONEMEB: ::std::os::raw::c_int = 0;
pub const AL_VOCAL_MORPHER_MAX_PHONEMEB: ::std::os::raw::c_int = 29;
pub const AL_VOCAL_MORPHER_DEFAULT_PHONEMEB: ::std::os::raw::c_int = 10;
pub const AL_VOCAL_MORPHER_MIN_PHONEMEB_COARSE_TUNING: ::std::os::raw::c_int =
    -24;
pub const AL_VOCAL_MORPHER_MAX_PHONEMEB_COARSE_TUNING: ::std::os::raw::c_int =
    24;
pub const AL_VOCAL_MORPHER_DEFAULT_PHONEMEB_COARSE_TUNING:
          ::std::os::raw::c_int =
    0;
pub const AL_VOCAL_MORPHER_PHONEME_A: ::std::os::raw::c_int = 0;
pub const AL_VOCAL_MORPHER_PHONEME_E: ::std::os::raw::c_int = 1;
pub const AL_VOCAL_MORPHER_PHONEME_I: ::std::os::raw::c_int = 2;
pub const AL_VOCAL_MORPHER_PHONEME_O: ::std::os::raw::c_int = 3;
pub const AL_VOCAL_MORPHER_PHONEME_U: ::std::os::raw::c_int = 4;
pub const AL_VOCAL_MORPHER_PHONEME_AA: ::std::os::raw::c_int = 5;
pub const AL_VOCAL_MORPHER_PHONEME_AE: ::std::os::raw::c_int = 6;
pub const AL_VOCAL_MORPHER_PHONEME_AH: ::std::os::raw::c_int = 7;
pub const AL_VOCAL_MORPHER_PHONEME_AO: ::std::os::raw::c_int = 8;
pub const AL_VOCAL_MORPHER_PHONEME_EH: ::std::os::raw::c_int = 9;
pub const AL_VOCAL_MORPHER_PHONEME_ER: ::std::os::raw::c_int = 10;
pub const AL_VOCAL_MORPHER_PHONEME_IH: ::std::os::raw::c_int = 11;
pub const AL_VOCAL_MORPHER_PHONEME_IY: ::std::os::raw::c_int = 12;
pub const AL_VOCAL_MORPHER_PHONEME_UH: ::std::os::raw::c_int = 13;
pub const AL_VOCAL_MORPHER_PHONEME_UW: ::std::os::raw::c_int = 14;
pub const AL_VOCAL_MORPHER_PHONEME_B: ::std::os::raw::c_int = 15;
pub const AL_VOCAL_MORPHER_PHONEME_D: ::std::os::raw::c_int = 16;
pub const AL_VOCAL_MORPHER_PHONEME_F: ::std::os::raw::c_int = 17;
pub const AL_VOCAL_MORPHER_PHONEME_G: ::std::os::raw::c_int = 18;
pub const AL_VOCAL_MORPHER_PHONEME_J: ::std::os::raw::c_int = 19;
pub const AL_VOCAL_MORPHER_PHONEME_K: ::std::os::raw::c_int = 20;
pub const AL_VOCAL_MORPHER_PHONEME_L: ::std::os::raw::c_int = 21;
pub const AL_VOCAL_MORPHER_PHONEME_M: ::std::os::raw::c_int = 22;
pub const AL_VOCAL_MORPHER_PHONEME_N: ::std::os::raw::c_int = 23;
pub const AL_VOCAL_MORPHER_PHONEME_P: ::std::os::raw::c_int = 24;
pub const AL_VOCAL_MORPHER_PHONEME_R: ::std::os::raw::c_int = 25;
pub const AL_VOCAL_MORPHER_PHONEME_S: ::std::os::raw::c_int = 26;
pub const AL_VOCAL_MORPHER_PHONEME_T: ::std::os::raw::c_int = 27;
pub const AL_VOCAL_MORPHER_PHONEME_V: ::std::os::raw::c_int = 28;
pub const AL_VOCAL_MORPHER_PHONEME_Z: ::std::os::raw::c_int = 29;
pub const AL_VOCAL_MORPHER_WAVEFORM_SINUSOID: ::std::os::raw::c_int = 0;
pub const AL_VOCAL_MORPHER_WAVEFORM_TRIANGLE: ::std::os::raw::c_int = 1;
pub const AL_VOCAL_MORPHER_WAVEFORM_SAWTOOTH: ::std::os::raw::c_int = 2;
pub const AL_VOCAL_MORPHER_MIN_WAVEFORM: ::std::os::raw::c_int = 0;
pub const AL_VOCAL_MORPHER_MAX_WAVEFORM: ::std::os::raw::c_int = 2;
pub const AL_VOCAL_MORPHER_DEFAULT_WAVEFORM: ::std::os::raw::c_int = 0;
pub const AL_PITCH_SHIFTER_MIN_COARSE_TUNE: ::std::os::raw::c_int = -12;
pub const AL_PITCH_SHIFTER_MAX_COARSE_TUNE: ::std::os::raw::c_int = 12;
pub const AL_PITCH_SHIFTER_DEFAULT_COARSE_TUNE: ::std::os::raw::c_int = 12;
pub const AL_PITCH_SHIFTER_MIN_FINE_TUNE: ::std::os::raw::c_int = -50;
pub const AL_PITCH_SHIFTER_MAX_FINE_TUNE: ::std::os::raw::c_int = 50;
pub const AL_PITCH_SHIFTER_DEFAULT_FINE_TUNE: ::std::os::raw::c_int = 0;
pub const AL_RING_MODULATOR_SINUSOID: ::std::os::raw::c_int = 0;
pub const AL_RING_MODULATOR_SAWTOOTH: ::std::os::raw::c_int = 1;
pub const AL_RING_MODULATOR_SQUARE: ::std::os::raw::c_int = 2;
pub const AL_RING_MODULATOR_MIN_WAVEFORM: ::std::os::raw::c_int = 0;
pub const AL_RING_MODULATOR_MAX_WAVEFORM: ::std::os::raw::c_int = 2;
pub const AL_RING_MODULATOR_DEFAULT_WAVEFORM: ::std::os::raw::c_int = 0;
pub const AL_COMPRESSOR_MIN_ONOFF: ::std::os::raw::c_int = 0;
pub const AL_COMPRESSOR_MAX_ONOFF: ::std::os::raw::c_int = 1;
pub const AL_COMPRESSOR_DEFAULT_ONOFF: ::std::os::raw::c_int = 1;
pub const ALC_EXT_disconnect: ::std::os::raw::c_int = 1;
pub const ALC_CONNECTED: ::std::os::raw::c_int = 787;
pub const ALC_EXT_thread_local_context: ::std::os::raw::c_int = 1;
pub const AL_EXT_source_distance_model: ::std::os::raw::c_int = 1;
pub const AL_SOURCE_DISTANCE_MODEL: ::std::os::raw::c_int = 512;
pub const AL_SOFT_buffer_sub_data: ::std::os::raw::c_int = 1;
pub const AL_BYTE_RW_OFFSETS_SOFT: ::std::os::raw::c_int = 4145;
pub const AL_SAMPLE_RW_OFFSETS_SOFT: ::std::os::raw::c_int = 4146;
pub const AL_SOFT_loop_points: ::std::os::raw::c_int = 1;
pub const AL_LOOP_POINTS_SOFT: ::std::os::raw::c_int = 8213;
pub const AL_EXT_FOLDBACK: ::std::os::raw::c_int = 1;
pub const AL_FOLDBACK_EVENT_BLOCK: ::std::os::raw::c_int = 16658;
pub const AL_FOLDBACK_EVENT_START: ::std::os::raw::c_int = 16657;
pub const AL_FOLDBACK_EVENT_STOP: ::std::os::raw::c_int = 16659;
pub const AL_FOLDBACK_MODE_MONO: ::std::os::raw::c_int = 16641;
pub const AL_FOLDBACK_MODE_STEREO: ::std::os::raw::c_int = 16642;
pub const ALC_EXT_DEDICATED: ::std::os::raw::c_int = 1;
pub const AL_DEDICATED_GAIN: ::std::os::raw::c_int = 1;
pub const AL_EFFECT_DEDICATED_DIALOGUE: ::std::os::raw::c_int = 36865;
pub const AL_EFFECT_DEDICATED_LOW_FREQUENCY_EFFECT: ::std::os::raw::c_int =
    36864;
pub const AL_SOFT_buffer_samples: ::std::os::raw::c_int = 1;
pub const AL_MONO_SOFT: ::std::os::raw::c_int = 5376;
pub const AL_STEREO_SOFT: ::std::os::raw::c_int = 5377;
pub const AL_REAR_SOFT: ::std::os::raw::c_int = 5378;
pub const AL_QUAD_SOFT: ::std::os::raw::c_int = 5379;
pub const AL_5POINT1_SOFT: ::std::os::raw::c_int = 5380;
pub const AL_6POINT1_SOFT: ::std::os::raw::c_int = 5381;
pub const AL_7POINT1_SOFT: ::std::os::raw::c_int = 5382;
pub const AL_BYTE_SOFT: ::std::os::raw::c_int = 5120;
pub const AL_UNSIGNED_BYTE_SOFT: ::std::os::raw::c_int = 5121;
pub const AL_SHORT_SOFT: ::std::os::raw::c_int = 5122;
pub const AL_UNSIGNED_SHORT_SOFT: ::std::os::raw::c_int = 5123;
pub const AL_INT_SOFT: ::std::os::raw::c_int = 5124;
pub const AL_UNSIGNED_INT_SOFT: ::std::os::raw::c_int = 5125;
pub const AL_FLOAT_SOFT: ::std::os::raw::c_int = 5126;
pub const AL_DOUBLE_SOFT: ::std::os::raw::c_int = 5127;
pub const AL_BYTE3_SOFT: ::std::os::raw::c_int = 5128;
pub const AL_UNSIGNED_BYTE3_SOFT: ::std::os::raw::c_int = 5129;
pub const AL_MONO8_SOFT: ::std::os::raw::c_int = 4352;
pub const AL_MONO16_SOFT: ::std::os::raw::c_int = 4353;
pub const AL_MONO32F_SOFT: ::std::os::raw::c_uint = 65552;
pub const AL_STEREO8_SOFT: ::std::os::raw::c_int = 4354;
pub const AL_STEREO16_SOFT: ::std::os::raw::c_int = 4355;
pub const AL_STEREO32F_SOFT: ::std::os::raw::c_uint = 65553;
pub const AL_QUAD8_SOFT: ::std::os::raw::c_int = 4612;
pub const AL_QUAD16_SOFT: ::std::os::raw::c_int = 4613;
pub const AL_QUAD32F_SOFT: ::std::os::raw::c_int = 4614;
pub const AL_REAR8_SOFT: ::std::os::raw::c_int = 4615;
pub const AL_REAR16_SOFT: ::std::os::raw::c_int = 4616;
pub const AL_REAR32F_SOFT: ::std::os::raw::c_int = 4617;
pub const AL_5POINT1_8_SOFT: ::std::os::raw::c_int = 4618;
pub const AL_5POINT1_16_SOFT: ::std::os::raw::c_int = 4619;
pub const AL_5POINT1_32F_SOFT: ::std::os::raw::c_int = 4620;
pub const AL_6POINT1_8_SOFT: ::std::os::raw::c_int = 4621;
pub const AL_6POINT1_16_SOFT: ::std::os::raw::c_int = 4622;
pub const AL_6POINT1_32F_SOFT: ::std::os::raw::c_int = 4623;
pub const AL_7POINT1_8_SOFT: ::std::os::raw::c_int = 4624;
pub const AL_7POINT1_16_SOFT: ::std::os::raw::c_int = 4625;
pub const AL_7POINT1_32F_SOFT: ::std::os::raw::c_int = 4626;
pub const AL_INTERNAL_FORMAT_SOFT: ::std::os::raw::c_int = 8200;
pub const AL_BYTE_LENGTH_SOFT: ::std::os::raw::c_int = 8201;
pub const AL_SAMPLE_LENGTH_SOFT: ::std::os::raw::c_int = 8202;
pub const AL_SEC_LENGTH_SOFT: ::std::os::raw::c_int = 8203;
pub const AL_SOFT_direct_channels: ::std::os::raw::c_int = 1;
pub const AL_DIRECT_CHANNELS_SOFT: ::std::os::raw::c_int = 4147;
pub const ALC_SOFT_loopback: ::std::os::raw::c_int = 1;
pub const ALC_FORMAT_CHANNELS_SOFT: ::std::os::raw::c_int = 6544;
pub const ALC_FORMAT_TYPE_SOFT: ::std::os::raw::c_int = 6545;
pub const ALC_BYTE_SOFT: ::std::os::raw::c_int = 5120;
pub const ALC_UNSIGNED_BYTE_SOFT: ::std::os::raw::c_int = 5121;
pub const ALC_SHORT_SOFT: ::std::os::raw::c_int = 5122;
pub const ALC_UNSIGNED_SHORT_SOFT: ::std::os::raw::c_int = 5123;
pub const ALC_INT_SOFT: ::std::os::raw::c_int = 5124;
pub const ALC_UNSIGNED_INT_SOFT: ::std::os::raw::c_int = 5125;
pub const ALC_FLOAT_SOFT: ::std::os::raw::c_int = 5126;
pub const ALC_MONO_SOFT: ::std::os::raw::c_int = 5376;
pub const ALC_STEREO_SOFT: ::std::os::raw::c_int = 5377;
pub const ALC_QUAD_SOFT: ::std::os::raw::c_int = 5379;
pub const ALC_5POINT1_SOFT: ::std::os::raw::c_int = 5380;
pub const ALC_6POINT1_SOFT: ::std::os::raw::c_int = 5381;
pub const ALC_7POINT1_SOFT: ::std::os::raw::c_int = 5382;
pub const AL_EXT_STEREO_ANGLES: ::std::os::raw::c_int = 1;
pub const AL_STEREO_ANGLES: ::std::os::raw::c_int = 4144;
pub const AL_EXT_SOURCE_RADIUS: ::std::os::raw::c_int = 1;
pub const AL_SOURCE_RADIUS: ::std::os::raw::c_int = 4145;
pub const AL_SOFT_source_latency: ::std::os::raw::c_int = 1;
pub const AL_SAMPLE_OFFSET_LATENCY_SOFT: ::std::os::raw::c_int = 4608;
pub const AL_SEC_OFFSET_LATENCY_SOFT: ::std::os::raw::c_int = 4609;
pub const ALC_EXT_DEFAULT_FILTER_ORDER: ::std::os::raw::c_int = 1;
pub const ALC_DEFAULT_FILTER_ORDER: ::std::os::raw::c_int = 4352;
pub const AL_SOFT_deferred_updates: ::std::os::raw::c_int = 1;
pub const AL_DEFERRED_UPDATES_SOFT: ::std::os::raw::c_int = 49154;
pub const AL_SOFT_block_alignment: ::std::os::raw::c_int = 1;
pub const AL_UNPACK_BLOCK_ALIGNMENT_SOFT: ::std::os::raw::c_int = 8204;
pub const AL_PACK_BLOCK_ALIGNMENT_SOFT: ::std::os::raw::c_int = 8205;
pub const AL_SOFT_MSADPCM: ::std::os::raw::c_int = 1;
pub const AL_FORMAT_MONO_MSADPCM_SOFT: ::std::os::raw::c_int = 4866;
pub const AL_FORMAT_STEREO_MSADPCM_SOFT: ::std::os::raw::c_int = 4867;
pub const AL_SOFT_source_length: ::std::os::raw::c_int = 1;
pub const ALC_SOFT_pause_device: ::std::os::raw::c_int = 1;
pub const AL_EXT_BFORMAT: ::std::os::raw::c_int = 1;
pub const AL_FORMAT_BFORMAT2D_8: ::std::os::raw::c_uint = 131105;
pub const AL_FORMAT_BFORMAT2D_16: ::std::os::raw::c_uint = 131106;
pub const AL_FORMAT_BFORMAT2D_FLOAT32: ::std::os::raw::c_uint = 131107;
pub const AL_FORMAT_BFORMAT3D_8: ::std::os::raw::c_uint = 131121;
pub const AL_FORMAT_BFORMAT3D_16: ::std::os::raw::c_uint = 131122;
pub const AL_FORMAT_BFORMAT3D_FLOAT32: ::std::os::raw::c_uint = 131123;
pub const AL_EXT_MULAW_BFORMAT: ::std::os::raw::c_int = 1;
pub const AL_FORMAT_BFORMAT2D_MULAW: ::std::os::raw::c_uint = 65585;
pub const AL_FORMAT_BFORMAT3D_MULAW: ::std::os::raw::c_uint = 65586;
pub const ALC_SOFT_HRTF: ::std::os::raw::c_int = 1;
pub const ALC_HRTF_SOFT: ::std::os::raw::c_int = 6546;
pub const ALC_DONT_CARE_SOFT: ::std::os::raw::c_int = 2;
pub const ALC_HRTF_STATUS_SOFT: ::std::os::raw::c_int = 6547;
pub const ALC_HRTF_DISABLED_SOFT: ::std::os::raw::c_int = 0;
pub const ALC_HRTF_ENABLED_SOFT: ::std::os::raw::c_int = 1;
pub const ALC_HRTF_DENIED_SOFT: ::std::os::raw::c_int = 2;
pub const ALC_HRTF_REQUIRED_SOFT: ::std::os::raw::c_int = 3;
pub const ALC_HRTF_HEADPHONES_DETECTED_SOFT: ::std::os::raw::c_int = 4;
pub const ALC_HRTF_UNSUPPORTED_FORMAT_SOFT: ::std::os::raw::c_int = 5;
pub const ALC_NUM_HRTF_SPECIFIERS_SOFT: ::std::os::raw::c_int = 6548;
pub const ALC_HRTF_SPECIFIER_SOFT: ::std::os::raw::c_int = 6549;
pub const ALC_HRTF_ID_SOFT: ::std::os::raw::c_int = 6550;
pub type ptrdiff_t = isize;
pub type size_t = usize;
pub type wchar_t = ::std::os::raw::c_int;
pub type int8_t = i8;
pub type int16_t = i16;
pub type int32_t = i32;
pub type int64_t = i64;
pub type uint8_t = u8;
pub type uint16_t = u16;
pub type uint32_t = u32;
pub type uint64_t = u64;
pub type int_least8_t = ::std::os::raw::c_char;
pub type int_least16_t = ::std::os::raw::c_short;
pub type int_least32_t = ::std::os::raw::c_int;
pub type int_least64_t = ::std::os::raw::c_long;
pub type uint_least8_t = ::std::os::raw::c_uchar;
pub type uint_least16_t = ::std::os::raw::c_ushort;
pub type uint_least32_t = ::std::os::raw::c_uint;
pub type uint_least64_t = ::std::os::raw::c_ulong;
pub type int_fast8_t = ::std::os::raw::c_char;
pub type int_fast16_t = ::std::os::raw::c_long;
pub type int_fast32_t = ::std::os::raw::c_long;
pub type int_fast64_t = ::std::os::raw::c_long;
pub type uint_fast8_t = ::std::os::raw::c_uchar;
pub type uint_fast16_t = ::std::os::raw::c_ulong;
pub type uint_fast32_t = ::std::os::raw::c_ulong;
pub type uint_fast64_t = ::std::os::raw::c_ulong;
pub type intptr_t = isize;
pub type uintptr_t = usize;
pub type intmax_t = ::std::os::raw::c_long;
pub type uintmax_t = ::std::os::raw::c_ulong;
pub type PFNALBUFFERDATASTATICPROC =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALint, arg2: ALenum,
                                               arg3: *mut ALvoid,
                                               arg4: ALsizei, arg5: ALsizei)
                              -> ALvoid>;
pub type LPALGENEFFECTS =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALsizei,
                                               arg2: *mut ALuint)>;
pub type LPALDELETEEFFECTS =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALsizei,
                                               arg2: *const ALuint)>;
pub type LPALISEFFECT =
    ::std::option::Option<extern "C" fn(arg1: ALuint) -> ALboolean>;
pub type LPALEFFECTI =
    ::std::option::Option<extern "C" fn(arg1: ALuint, arg2: ALenum,
                                        arg3: ALint)>;
pub type LPALEFFECTIV =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *const ALint)>;
pub type LPALEFFECTF =
    ::std::option::Option<extern "C" fn(arg1: ALuint, arg2: ALenum,
                                        arg3: ALfloat)>;
pub type LPALEFFECTFV =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *const ALfloat)>;
pub type LPALGETEFFECTI =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *mut ALint)>;
pub type LPALGETEFFECTIV =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *mut ALint)>;
pub type LPALGETEFFECTF =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *mut ALfloat)>;
pub type LPALGETEFFECTFV =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *mut ALfloat)>;
pub type LPALGENFILTERS =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALsizei,
                                               arg2: *mut ALuint)>;
pub type LPALDELETEFILTERS =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALsizei,
                                               arg2: *const ALuint)>;
pub type LPALISFILTER =
    ::std::option::Option<extern "C" fn(arg1: ALuint) -> ALboolean>;
pub type LPALFILTERI =
    ::std::option::Option<extern "C" fn(arg1: ALuint, arg2: ALenum,
                                        arg3: ALint)>;
pub type LPALFILTERIV =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *const ALint)>;
pub type LPALFILTERF =
    ::std::option::Option<extern "C" fn(arg1: ALuint, arg2: ALenum,
                                        arg3: ALfloat)>;
pub type LPALFILTERFV =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *const ALfloat)>;
pub type LPALGETFILTERI =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *mut ALint)>;
pub type LPALGETFILTERIV =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *mut ALint)>;
pub type LPALGETFILTERF =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *mut ALfloat)>;
pub type LPALGETFILTERFV =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *mut ALfloat)>;
pub type LPALGENAUXILIARYEFFECTSLOTS =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALsizei,
                                               arg2: *mut ALuint)>;
pub type LPALDELETEAUXILIARYEFFECTSLOTS =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALsizei,
                                               arg2: *const ALuint)>;
pub type LPALISAUXILIARYEFFECTSLOT =
    ::std::option::Option<extern "C" fn(arg1: ALuint) -> ALboolean>;
pub type LPALAUXILIARYEFFECTSLOTI =
    ::std::option::Option<extern "C" fn(arg1: ALuint, arg2: ALenum,
                                        arg3: ALint)>;
pub type LPALAUXILIARYEFFECTSLOTIV =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *const ALint)>;
pub type LPALAUXILIARYEFFECTSLOTF =
    ::std::option::Option<extern "C" fn(arg1: ALuint, arg2: ALenum,
                                        arg3: ALfloat)>;
pub type LPALAUXILIARYEFFECTSLOTFV =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *const ALfloat)>;
pub type LPALGETAUXILIARYEFFECTSLOTI =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *mut ALint)>;
pub type LPALGETAUXILIARYEFFECTSLOTIV =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *mut ALint)>;
pub type LPALGETAUXILIARYEFFECTSLOTF =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *mut ALfloat)>;
pub type LPALGETAUXILIARYEFFECTSLOTFV =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *mut ALfloat)>;
pub type PFNALCSETTHREADCONTEXTPROC =
    ::std::option::Option<unsafe extern "C" fn(context: *mut ALCcontext)
                              -> ALCboolean>;
pub type PFNALCGETTHREADCONTEXTPROC =
    ::std::option::Option<extern "C" fn() -> *mut ALCcontext>;
pub type PFNALBUFFERSUBDATASOFTPROC =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *const ALvoid,
                                               arg4: ALsizei, arg5: ALsizei)
                              -> ALvoid>;
pub type LPALFOLDBACKCALLBACK =
    ::std::option::Option<extern "C" fn(arg1: ALenum, arg2: ALsizei)>;
pub type LPALREQUESTFOLDBACKSTART =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALenum, arg2: ALsizei,
                                               arg3: ALsizei,
                                               arg4: *mut ALfloat,
                                               arg5: LPALFOLDBACKCALLBACK)>;
pub type LPALREQUESTFOLDBACKSTOP = ::std::option::Option<extern "C" fn()>;
pub type LPALBUFFERSAMPLESSOFT =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALuint,
                                               arg3: ALenum, arg4: ALsizei,
                                               arg5: ALenum, arg6: ALenum,
                                               arg7: *const ALvoid)>;
pub type LPALBUFFERSUBSAMPLESSOFT =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALsizei,
                                               arg3: ALsizei, arg4: ALenum,
                                               arg5: ALenum,
                                               arg6: *const ALvoid)>;
pub type LPALGETBUFFERSAMPLESSOFT =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALsizei,
                                               arg3: ALsizei, arg4: ALenum,
                                               arg5: ALenum,
                                               arg6: *mut ALvoid)>;
pub type LPALISBUFFERFORMATSUPPORTEDSOFT =
    ::std::option::Option<extern "C" fn(arg1: ALenum) -> ALboolean>;
pub type LPALCLOOPBACKOPENDEVICESOFT =
    ::std::option::Option<unsafe extern "C" fn(arg1: *const ALCchar)
                              -> *mut ALCdevice>;
pub type LPALCISRENDERFORMATSUPPORTEDSOFT =
    ::std::option::Option<unsafe extern "C" fn(arg1: *mut ALCdevice,
                                               arg2: ALCsizei, arg3: ALCenum,
                                               arg4: ALCenum) -> ALCboolean>;
pub type LPALCRENDERSAMPLESSOFT =
    ::std::option::Option<unsafe extern "C" fn(arg1: *mut ALCdevice,
                                               arg2: *mut ALCvoid,
                                               arg3: ALCsizei)>;
pub type ALint64SOFT = int64_t;
pub type ALuint64SOFT = uint64_t;
pub type LPALSOURCEDSOFT =
    ::std::option::Option<extern "C" fn(arg1: ALuint, arg2: ALenum,
                                        arg3: ALdouble)>;
pub type LPALSOURCE3DSOFT =
    ::std::option::Option<extern "C" fn(arg1: ALuint, arg2: ALenum,
                                        arg3: ALdouble, arg4: ALdouble,
                                        arg5: ALdouble)>;
pub type LPALSOURCEDVSOFT =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *const ALdouble)>;
pub type LPALGETSOURCEDSOFT =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *mut ALdouble)>;
pub type LPALGETSOURCE3DSOFT =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *mut ALdouble,
                                               arg4: *mut ALdouble,
                                               arg5: *mut ALdouble)>;
pub type LPALGETSOURCEDVSOFT =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *mut ALdouble)>;
pub type LPALSOURCEI64SOFT =
    ::std::option::Option<extern "C" fn(arg1: ALuint, arg2: ALenum,
                                        arg3: ALint64SOFT)>;
pub type LPALSOURCE3I64SOFT =
    ::std::option::Option<extern "C" fn(arg1: ALuint, arg2: ALenum,
                                        arg3: ALint64SOFT, arg4: ALint64SOFT,
                                        arg5: ALint64SOFT)>;
pub type LPALSOURCEI64VSOFT =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *const ALint64SOFT)>;
pub type LPALGETSOURCEI64SOFT =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *mut ALint64SOFT)>;
pub type LPALGETSOURCE3I64SOFT =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *mut ALint64SOFT,
                                               arg4: *mut ALint64SOFT,
                                               arg5: *mut ALint64SOFT)>;
pub type LPALGETSOURCEI64VSOFT =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *mut ALint64SOFT)>;
pub type LPALDEFERUPDATESSOFT =
    ::std::option::Option<extern "C" fn() -> ALvoid>;
pub type LPALPROCESSUPDATESSOFT =
    ::std::option::Option<extern "C" fn() -> ALvoid>;
pub type LPALCDEVICEPAUSESOFT =
    ::std::option::Option<unsafe extern "C" fn(device: *mut ALCdevice)>;
pub type LPALCDEVICERESUMESOFT =
    ::std::option::Option<unsafe extern "C" fn(device: *mut ALCdevice)>;
pub type LPALCGETSTRINGISOFT =
    ::std::option::Option<unsafe extern "C" fn(device: *mut ALCdevice,
                                               paramName: ALCenum,
                                               index: ALCsizei)
                              -> *const ALCchar>;
pub type LPALCRESETDEVICESOFT =
    ::std::option::Option<unsafe extern "C" fn(device: *mut ALCdevice,
                                               attribs: *const ALCint)
                              -> ALCboolean>;
