/* automatically generated by rust-bindgen */

#![allow(dead_code,
         non_camel_case_types,
         non_upper_case_globals,
         non_snake_case)]

use al::*;
use alc::*;

pub const _STDINT_H: ::std::os::raw::c_uchar = 1;
pub const INT8_MIN: ::std::os::raw::c_char = -128;
pub const INT16_MIN: ::std::os::raw::c_short = -32768;
pub const INT32_MIN: ::std::os::raw::c_int = -2147483648;
pub const INT8_MAX: ::std::os::raw::c_uchar = 127;
pub const INT16_MAX: ::std::os::raw::c_ushort = 32767;
pub const INT32_MAX: ::std::os::raw::c_uint = 2147483647;
pub const UINT8_MAX: ::std::os::raw::c_uchar = 255;
pub const UINT16_MAX: ::std::os::raw::c_ushort = 65535;
pub const UINT32_MAX: ::std::os::raw::c_uint = 4294967295;
pub const INT_LEAST8_MIN: ::std::os::raw::c_char = -128;
pub const INT_LEAST16_MIN: ::std::os::raw::c_short = -32768;
pub const INT_LEAST32_MIN: ::std::os::raw::c_int = -2147483648;
pub const INT_LEAST8_MAX: ::std::os::raw::c_uchar = 127;
pub const INT_LEAST16_MAX: ::std::os::raw::c_ushort = 32767;
pub const INT_LEAST32_MAX: ::std::os::raw::c_uint = 2147483647;
pub const UINT_LEAST8_MAX: ::std::os::raw::c_uchar = 255;
pub const UINT_LEAST16_MAX: ::std::os::raw::c_ushort = 65535;
pub const UINT_LEAST32_MAX: ::std::os::raw::c_uint = 4294967295;
pub const INT_FAST8_MIN: ::std::os::raw::c_char = -128;
pub const INT_FAST16_MIN: ::std::os::raw::c_longlong = -9223372036854775808;
pub const INT_FAST32_MIN: ::std::os::raw::c_longlong = -9223372036854775808;
pub const INT_FAST8_MAX: ::std::os::raw::c_uchar = 127;
pub const INT_FAST16_MAX: ::std::os::raw::c_ulonglong = 9223372036854775807;
pub const INT_FAST32_MAX: ::std::os::raw::c_ulonglong = 9223372036854775807;
pub const UINT_FAST8_MAX: ::std::os::raw::c_uchar = 255;
pub const UINT_FAST16_MAX: ::std::os::raw::c_char = -1;
pub const UINT_FAST32_MAX: ::std::os::raw::c_char = -1;
pub const INTPTR_MIN: ::std::os::raw::c_longlong = -9223372036854775808;
pub const INTPTR_MAX: ::std::os::raw::c_ulonglong = 9223372036854775807;
pub const UINTPTR_MAX: ::std::os::raw::c_char = -1;
pub const PTRDIFF_MIN: ::std::os::raw::c_longlong = -9223372036854775808;
pub const PTRDIFF_MAX: ::std::os::raw::c_ulonglong = 9223372036854775807;
pub const SIG_ATOMIC_MIN: ::std::os::raw::c_int = -2147483648;
pub const SIG_ATOMIC_MAX: ::std::os::raw::c_uint = 2147483647;
pub const SIZE_MAX: ::std::os::raw::c_char = -1;
pub const WINT_MIN: ::std::os::raw::c_uchar = 0;
pub const WINT_MAX: ::std::os::raw::c_uint = 4294967295;
pub const AL_LOKI_IMA_ADPCM_format: ::std::os::raw::c_uchar = 1;
pub const AL_FORMAT_IMA_ADPCM_MONO16_EXT: ::std::os::raw::c_uint = 65536;
pub const AL_FORMAT_IMA_ADPCM_STEREO16_EXT: ::std::os::raw::c_uint = 65537;
pub const AL_LOKI_WAVE_format: ::std::os::raw::c_uchar = 1;
pub const AL_FORMAT_WAVE_EXT: ::std::os::raw::c_uint = 65538;
pub const AL_EXT_vorbis: ::std::os::raw::c_uchar = 1;
pub const AL_FORMAT_VORBIS_EXT: ::std::os::raw::c_uint = 65539;
pub const AL_LOKI_quadriphonic: ::std::os::raw::c_uchar = 1;
pub const AL_FORMAT_QUAD8_LOKI: ::std::os::raw::c_uint = 65540;
pub const AL_FORMAT_QUAD16_LOKI: ::std::os::raw::c_uint = 65541;
pub const AL_EXT_float32: ::std::os::raw::c_uchar = 1;
pub const AL_FORMAT_MONO_FLOAT32: ::std::os::raw::c_uint = 65552;
pub const AL_FORMAT_STEREO_FLOAT32: ::std::os::raw::c_uint = 65553;
pub const AL_EXT_double: ::std::os::raw::c_uchar = 1;
pub const AL_FORMAT_MONO_DOUBLE_EXT: ::std::os::raw::c_uint = 65554;
pub const AL_FORMAT_STEREO_DOUBLE_EXT: ::std::os::raw::c_uint = 65555;
pub const AL_EXT_MULAW: ::std::os::raw::c_uchar = 1;
pub const AL_FORMAT_MONO_MULAW_EXT: ::std::os::raw::c_uint = 65556;
pub const AL_FORMAT_STEREO_MULAW_EXT: ::std::os::raw::c_uint = 65557;
pub const AL_EXT_ALAW: ::std::os::raw::c_uchar = 1;
pub const AL_FORMAT_MONO_ALAW_EXT: ::std::os::raw::c_uint = 65558;
pub const AL_FORMAT_STEREO_ALAW_EXT: ::std::os::raw::c_uint = 65559;
pub const ALC_LOKI_audio_channel: ::std::os::raw::c_uchar = 1;
pub const ALC_CHAN_MAIN_LOKI: ::std::os::raw::c_uint = 5242881;
pub const ALC_CHAN_PCM_LOKI: ::std::os::raw::c_uint = 5242882;
pub const ALC_CHAN_CD_LOKI: ::std::os::raw::c_uint = 5242883;
pub const AL_EXT_MCFORMATS: ::std::os::raw::c_uchar = 1;
pub const AL_FORMAT_QUAD8: ::std::os::raw::c_ushort = 4612;
pub const AL_FORMAT_QUAD16: ::std::os::raw::c_ushort = 4613;
pub const AL_FORMAT_QUAD32: ::std::os::raw::c_ushort = 4614;
pub const AL_FORMAT_REAR8: ::std::os::raw::c_ushort = 4615;
pub const AL_FORMAT_REAR16: ::std::os::raw::c_ushort = 4616;
pub const AL_FORMAT_REAR32: ::std::os::raw::c_ushort = 4617;
pub const AL_FORMAT_51CHN8: ::std::os::raw::c_ushort = 4618;
pub const AL_FORMAT_51CHN16: ::std::os::raw::c_ushort = 4619;
pub const AL_FORMAT_51CHN32: ::std::os::raw::c_ushort = 4620;
pub const AL_FORMAT_61CHN8: ::std::os::raw::c_ushort = 4621;
pub const AL_FORMAT_61CHN16: ::std::os::raw::c_ushort = 4622;
pub const AL_FORMAT_61CHN32: ::std::os::raw::c_ushort = 4623;
pub const AL_FORMAT_71CHN8: ::std::os::raw::c_ushort = 4624;
pub const AL_FORMAT_71CHN16: ::std::os::raw::c_ushort = 4625;
pub const AL_FORMAT_71CHN32: ::std::os::raw::c_ushort = 4626;
pub const AL_EXT_MULAW_MCFORMATS: ::std::os::raw::c_uchar = 1;
pub const AL_FORMAT_MONO_MULAW: ::std::os::raw::c_uint = 65556;
pub const AL_FORMAT_STEREO_MULAW: ::std::os::raw::c_uint = 65557;
pub const AL_FORMAT_QUAD_MULAW: ::std::os::raw::c_uint = 65569;
pub const AL_FORMAT_REAR_MULAW: ::std::os::raw::c_uint = 65570;
pub const AL_FORMAT_51CHN_MULAW: ::std::os::raw::c_uint = 65571;
pub const AL_FORMAT_61CHN_MULAW: ::std::os::raw::c_uint = 65572;
pub const AL_FORMAT_71CHN_MULAW: ::std::os::raw::c_uint = 65573;
pub const AL_EXT_IMA4: ::std::os::raw::c_uchar = 1;
pub const AL_FORMAT_MONO_IMA4: ::std::os::raw::c_ushort = 4864;
pub const AL_FORMAT_STEREO_IMA4: ::std::os::raw::c_ushort = 4865;
pub const AL_EXT_STATIC_BUFFER: ::std::os::raw::c_uchar = 1;
pub const ALC_EXT_EFX: ::std::os::raw::c_uchar = 1;
pub const ALC_EXT_disconnect: ::std::os::raw::c_uchar = 1;
pub const ALC_CONNECTED: ::std::os::raw::c_ushort = 787;
pub const ALC_EXT_thread_local_context: ::std::os::raw::c_uchar = 1;
pub const AL_EXT_source_distance_model: ::std::os::raw::c_uchar = 1;
pub const AL_SOURCE_DISTANCE_MODEL: ::std::os::raw::c_ushort = 512;
pub const AL_SOFT_buffer_sub_data: ::std::os::raw::c_uchar = 1;
pub const AL_BYTE_RW_OFFSETS_SOFT: ::std::os::raw::c_ushort = 4145;
pub const AL_SAMPLE_RW_OFFSETS_SOFT: ::std::os::raw::c_ushort = 4146;
pub const AL_SOFT_loop_points: ::std::os::raw::c_uchar = 1;
pub const AL_LOOP_POINTS_SOFT: ::std::os::raw::c_ushort = 8213;
pub const AL_EXT_FOLDBACK: ::std::os::raw::c_uchar = 1;
pub const AL_FOLDBACK_EVENT_BLOCK: ::std::os::raw::c_ushort = 16658;
pub const AL_FOLDBACK_EVENT_START: ::std::os::raw::c_ushort = 16657;
pub const AL_FOLDBACK_EVENT_STOP: ::std::os::raw::c_ushort = 16659;
pub const AL_FOLDBACK_MODE_MONO: ::std::os::raw::c_ushort = 16641;
pub const AL_FOLDBACK_MODE_STEREO: ::std::os::raw::c_ushort = 16642;
pub const ALC_EXT_DEDICATED: ::std::os::raw::c_uchar = 1;
pub const AL_DEDICATED_GAIN: ::std::os::raw::c_uchar = 1;
pub const AL_EFFECT_DEDICATED_DIALOGUE: ::std::os::raw::c_ushort = 36865;
pub const AL_EFFECT_DEDICATED_LOW_FREQUENCY_EFFECT: ::std::os::raw::c_ushort =
    36864;
pub const AL_SOFT_buffer_samples: ::std::os::raw::c_uchar = 1;
pub const AL_MONO_SOFT: ::std::os::raw::c_ushort = 5376;
pub const AL_STEREO_SOFT: ::std::os::raw::c_ushort = 5377;
pub const AL_REAR_SOFT: ::std::os::raw::c_ushort = 5378;
pub const AL_QUAD_SOFT: ::std::os::raw::c_ushort = 5379;
pub const AL_5POINT1_SOFT: ::std::os::raw::c_ushort = 5380;
pub const AL_6POINT1_SOFT: ::std::os::raw::c_ushort = 5381;
pub const AL_7POINT1_SOFT: ::std::os::raw::c_ushort = 5382;
pub const AL_BYTE_SOFT: ::std::os::raw::c_ushort = 5120;
pub const AL_UNSIGNED_BYTE_SOFT: ::std::os::raw::c_ushort = 5121;
pub const AL_SHORT_SOFT: ::std::os::raw::c_ushort = 5122;
pub const AL_UNSIGNED_SHORT_SOFT: ::std::os::raw::c_ushort = 5123;
pub const AL_INT_SOFT: ::std::os::raw::c_ushort = 5124;
pub const AL_UNSIGNED_INT_SOFT: ::std::os::raw::c_ushort = 5125;
pub const AL_FLOAT_SOFT: ::std::os::raw::c_ushort = 5126;
pub const AL_DOUBLE_SOFT: ::std::os::raw::c_ushort = 5127;
pub const AL_BYTE3_SOFT: ::std::os::raw::c_ushort = 5128;
pub const AL_UNSIGNED_BYTE3_SOFT: ::std::os::raw::c_ushort = 5129;
pub const AL_MONO8_SOFT: ::std::os::raw::c_ushort = 4352;
pub const AL_MONO16_SOFT: ::std::os::raw::c_ushort = 4353;
pub const AL_MONO32F_SOFT: ::std::os::raw::c_uint = 65552;
pub const AL_STEREO8_SOFT: ::std::os::raw::c_ushort = 4354;
pub const AL_STEREO16_SOFT: ::std::os::raw::c_ushort = 4355;
pub const AL_STEREO32F_SOFT: ::std::os::raw::c_uint = 65553;
pub const AL_QUAD8_SOFT: ::std::os::raw::c_ushort = 4612;
pub const AL_QUAD16_SOFT: ::std::os::raw::c_ushort = 4613;
pub const AL_QUAD32F_SOFT: ::std::os::raw::c_ushort = 4614;
pub const AL_REAR8_SOFT: ::std::os::raw::c_ushort = 4615;
pub const AL_REAR16_SOFT: ::std::os::raw::c_ushort = 4616;
pub const AL_REAR32F_SOFT: ::std::os::raw::c_ushort = 4617;
pub const AL_5POINT1_8_SOFT: ::std::os::raw::c_ushort = 4618;
pub const AL_5POINT1_16_SOFT: ::std::os::raw::c_ushort = 4619;
pub const AL_5POINT1_32F_SOFT: ::std::os::raw::c_ushort = 4620;
pub const AL_6POINT1_8_SOFT: ::std::os::raw::c_ushort = 4621;
pub const AL_6POINT1_16_SOFT: ::std::os::raw::c_ushort = 4622;
pub const AL_6POINT1_32F_SOFT: ::std::os::raw::c_ushort = 4623;
pub const AL_7POINT1_8_SOFT: ::std::os::raw::c_ushort = 4624;
pub const AL_7POINT1_16_SOFT: ::std::os::raw::c_ushort = 4625;
pub const AL_7POINT1_32F_SOFT: ::std::os::raw::c_ushort = 4626;
pub const AL_INTERNAL_FORMAT_SOFT: ::std::os::raw::c_ushort = 8200;
pub const AL_BYTE_LENGTH_SOFT: ::std::os::raw::c_ushort = 8201;
pub const AL_SAMPLE_LENGTH_SOFT: ::std::os::raw::c_ushort = 8202;
pub const AL_SEC_LENGTH_SOFT: ::std::os::raw::c_ushort = 8203;
pub const AL_SOFT_direct_channels: ::std::os::raw::c_uchar = 1;
pub const AL_DIRECT_CHANNELS_SOFT: ::std::os::raw::c_ushort = 4147;
pub const ALC_SOFT_loopback: ::std::os::raw::c_uchar = 1;
pub const ALC_FORMAT_CHANNELS_SOFT: ::std::os::raw::c_ushort = 6544;
pub const ALC_FORMAT_TYPE_SOFT: ::std::os::raw::c_ushort = 6545;
pub const ALC_BYTE_SOFT: ::std::os::raw::c_ushort = 5120;
pub const ALC_UNSIGNED_BYTE_SOFT: ::std::os::raw::c_ushort = 5121;
pub const ALC_SHORT_SOFT: ::std::os::raw::c_ushort = 5122;
pub const ALC_UNSIGNED_SHORT_SOFT: ::std::os::raw::c_ushort = 5123;
pub const ALC_INT_SOFT: ::std::os::raw::c_ushort = 5124;
pub const ALC_UNSIGNED_INT_SOFT: ::std::os::raw::c_ushort = 5125;
pub const ALC_FLOAT_SOFT: ::std::os::raw::c_ushort = 5126;
pub const ALC_MONO_SOFT: ::std::os::raw::c_ushort = 5376;
pub const ALC_STEREO_SOFT: ::std::os::raw::c_ushort = 5377;
pub const ALC_QUAD_SOFT: ::std::os::raw::c_ushort = 5379;
pub const ALC_5POINT1_SOFT: ::std::os::raw::c_ushort = 5380;
pub const ALC_6POINT1_SOFT: ::std::os::raw::c_ushort = 5381;
pub const ALC_7POINT1_SOFT: ::std::os::raw::c_ushort = 5382;
pub const AL_EXT_STEREO_ANGLES: ::std::os::raw::c_uchar = 1;
pub const AL_STEREO_ANGLES: ::std::os::raw::c_ushort = 4144;
pub const AL_EXT_SOURCE_RADIUS: ::std::os::raw::c_uchar = 1;
pub const AL_SOURCE_RADIUS: ::std::os::raw::c_ushort = 4145;
pub const AL_SOFT_source_latency: ::std::os::raw::c_uchar = 1;
pub const AL_SAMPLE_OFFSET_LATENCY_SOFT: ::std::os::raw::c_ushort = 4608;
pub const AL_SEC_OFFSET_LATENCY_SOFT: ::std::os::raw::c_ushort = 4609;
pub const ALC_EXT_DEFAULT_FILTER_ORDER: ::std::os::raw::c_uchar = 1;
pub const ALC_DEFAULT_FILTER_ORDER: ::std::os::raw::c_ushort = 4352;
pub const AL_SOFT_deferred_updates: ::std::os::raw::c_uchar = 1;
pub const AL_DEFERRED_UPDATES_SOFT: ::std::os::raw::c_ushort = 49154;
pub const AL_SOFT_block_alignment: ::std::os::raw::c_uchar = 1;
pub const AL_UNPACK_BLOCK_ALIGNMENT_SOFT: ::std::os::raw::c_ushort = 8204;
pub const AL_PACK_BLOCK_ALIGNMENT_SOFT: ::std::os::raw::c_ushort = 8205;
pub const AL_SOFT_MSADPCM: ::std::os::raw::c_uchar = 1;
pub const AL_FORMAT_MONO_MSADPCM_SOFT: ::std::os::raw::c_ushort = 4866;
pub const AL_FORMAT_STEREO_MSADPCM_SOFT: ::std::os::raw::c_ushort = 4867;
pub const AL_SOFT_source_length: ::std::os::raw::c_uchar = 1;
pub const ALC_SOFT_pause_device: ::std::os::raw::c_uchar = 1;
pub const AL_EXT_BFORMAT: ::std::os::raw::c_uchar = 1;
pub const AL_FORMAT_BFORMAT2D_8: ::std::os::raw::c_uint = 131105;
pub const AL_FORMAT_BFORMAT2D_16: ::std::os::raw::c_uint = 131106;
pub const AL_FORMAT_BFORMAT2D_FLOAT32: ::std::os::raw::c_uint = 131107;
pub const AL_FORMAT_BFORMAT3D_8: ::std::os::raw::c_uint = 131121;
pub const AL_FORMAT_BFORMAT3D_16: ::std::os::raw::c_uint = 131122;
pub const AL_FORMAT_BFORMAT3D_FLOAT32: ::std::os::raw::c_uint = 131123;
pub const AL_EXT_MULAW_BFORMAT: ::std::os::raw::c_uchar = 1;
pub const AL_FORMAT_BFORMAT2D_MULAW: ::std::os::raw::c_uint = 65585;
pub const AL_FORMAT_BFORMAT3D_MULAW: ::std::os::raw::c_uint = 65586;
pub const ALC_SOFT_HRTF: ::std::os::raw::c_uchar = 1;
pub const ALC_HRTF_SOFT: ::std::os::raw::c_ushort = 6546;
pub const ALC_DONT_CARE_SOFT: ::std::os::raw::c_uchar = 2;
pub const ALC_HRTF_STATUS_SOFT: ::std::os::raw::c_ushort = 6547;
pub const ALC_HRTF_DISABLED_SOFT: ::std::os::raw::c_uchar = 0;
pub const ALC_HRTF_ENABLED_SOFT: ::std::os::raw::c_uchar = 1;
pub const ALC_HRTF_DENIED_SOFT: ::std::os::raw::c_uchar = 2;
pub const ALC_HRTF_REQUIRED_SOFT: ::std::os::raw::c_uchar = 3;
pub const ALC_HRTF_HEADPHONES_DETECTED_SOFT: ::std::os::raw::c_uchar = 4;
pub const ALC_HRTF_UNSUPPORTED_FORMAT_SOFT: ::std::os::raw::c_uchar = 5;
pub const ALC_NUM_HRTF_SPECIFIERS_SOFT: ::std::os::raw::c_ushort = 6548;
pub const ALC_HRTF_SPECIFIER_SOFT: ::std::os::raw::c_ushort = 6549;
pub const ALC_HRTF_ID_SOFT: ::std::os::raw::c_ushort = 6550;
pub type ptrdiff_t = isize;
pub type size_t = usize;
pub type wchar_t = ::std::os::raw::c_int;
pub type int8_t = i8;
pub type int16_t = i16;
pub type int32_t = i32;
pub type int64_t = i64;
pub type uint8_t = u8;
pub type uint16_t = u16;
pub type uint32_t = u32;
pub type uint64_t = u64;
pub type int_least8_t = ::std::os::raw::c_char;
pub type int_least16_t = ::std::os::raw::c_short;
pub type int_least32_t = ::std::os::raw::c_int;
pub type int_least64_t = ::std::os::raw::c_long;
pub type uint_least8_t = ::std::os::raw::c_uchar;
pub type uint_least16_t = ::std::os::raw::c_ushort;
pub type uint_least32_t = ::std::os::raw::c_uint;
pub type uint_least64_t = ::std::os::raw::c_ulong;
pub type int_fast8_t = ::std::os::raw::c_char;
pub type int_fast16_t = ::std::os::raw::c_long;
pub type int_fast32_t = ::std::os::raw::c_long;
pub type int_fast64_t = ::std::os::raw::c_long;
pub type uint_fast8_t = ::std::os::raw::c_uchar;
pub type uint_fast16_t = ::std::os::raw::c_ulong;
pub type uint_fast32_t = ::std::os::raw::c_ulong;
pub type uint_fast64_t = ::std::os::raw::c_ulong;
pub type intptr_t = isize;
pub type uintptr_t = usize;
pub type intmax_t = ::std::os::raw::c_long;
pub type uintmax_t = ::std::os::raw::c_ulong;
pub type PFNALBUFFERDATASTATICPROC =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALint, arg2: ALenum,
                                               arg3: *mut ALvoid,
                                               arg4: ALsizei, arg5: ALsizei)
                              -> ALvoid>;
pub type PFNALCSETTHREADCONTEXTPROC =
    ::std::option::Option<unsafe extern "C" fn(context: *mut ALCcontext)
                              -> ALCboolean>;
pub type PFNALCGETTHREADCONTEXTPROC =
    ::std::option::Option<extern "C" fn() -> *mut ALCcontext>;
pub type PFNALBUFFERSUBDATASOFTPROC =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *const ALvoid,
                                               arg4: ALsizei, arg5: ALsizei)
                              -> ALvoid>;
pub type LPALFOLDBACKCALLBACK =
    ::std::option::Option<extern "C" fn(arg1: ALenum, arg2: ALsizei)>;
pub type LPALREQUESTFOLDBACKSTART =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALenum, arg2: ALsizei,
                                               arg3: ALsizei,
                                               arg4: *mut ALfloat,
                                               arg5: LPALFOLDBACKCALLBACK)>;
pub type LPALREQUESTFOLDBACKSTOP = ::std::option::Option<extern "C" fn()>;
pub type LPALBUFFERSAMPLESSOFT =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALuint,
                                               arg3: ALenum, arg4: ALsizei,
                                               arg5: ALenum, arg6: ALenum,
                                               arg7: *const ALvoid)>;
pub type LPALBUFFERSUBSAMPLESSOFT =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALsizei,
                                               arg3: ALsizei, arg4: ALenum,
                                               arg5: ALenum,
                                               arg6: *const ALvoid)>;
pub type LPALGETBUFFERSAMPLESSOFT =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALsizei,
                                               arg3: ALsizei, arg4: ALenum,
                                               arg5: ALenum,
                                               arg6: *mut ALvoid)>;
pub type LPALISBUFFERFORMATSUPPORTEDSOFT =
    ::std::option::Option<extern "C" fn(arg1: ALenum) -> ALboolean>;
pub type LPALCLOOPBACKOPENDEVICESOFT =
    ::std::option::Option<unsafe extern "C" fn(arg1: *const ALCchar)
                              -> *mut ALCdevice>;
pub type LPALCISRENDERFORMATSUPPORTEDSOFT =
    ::std::option::Option<unsafe extern "C" fn(arg1: *mut ALCdevice,
                                               arg2: ALCsizei, arg3: ALCenum,
                                               arg4: ALCenum) -> ALCboolean>;
pub type LPALCRENDERSAMPLESSOFT =
    ::std::option::Option<unsafe extern "C" fn(arg1: *mut ALCdevice,
                                               arg2: *mut ALCvoid,
                                               arg3: ALCsizei)>;
pub type ALint64SOFT = int64_t;
pub type ALuint64SOFT = uint64_t;
pub type LPALSOURCEDSOFT =
    ::std::option::Option<extern "C" fn(arg1: ALuint, arg2: ALenum,
                                        arg3: ALdouble)>;
pub type LPALSOURCE3DSOFT =
    ::std::option::Option<extern "C" fn(arg1: ALuint, arg2: ALenum,
                                        arg3: ALdouble, arg4: ALdouble,
                                        arg5: ALdouble)>;
pub type LPALSOURCEDVSOFT =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *const ALdouble)>;
pub type LPALGETSOURCEDSOFT =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *mut ALdouble)>;
pub type LPALGETSOURCE3DSOFT =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *mut ALdouble,
                                               arg4: *mut ALdouble,
                                               arg5: *mut ALdouble)>;
pub type LPALGETSOURCEDVSOFT =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *mut ALdouble)>;
pub type LPALSOURCEI64SOFT =
    ::std::option::Option<extern "C" fn(arg1: ALuint, arg2: ALenum,
                                        arg3: ALint64SOFT)>;
pub type LPALSOURCE3I64SOFT =
    ::std::option::Option<extern "C" fn(arg1: ALuint, arg2: ALenum,
                                        arg3: ALint64SOFT, arg4: ALint64SOFT,
                                        arg5: ALint64SOFT)>;
pub type LPALSOURCEI64VSOFT =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *const ALint64SOFT)>;
pub type LPALGETSOURCEI64SOFT =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *mut ALint64SOFT)>;
pub type LPALGETSOURCE3I64SOFT =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *mut ALint64SOFT,
                                               arg4: *mut ALint64SOFT,
                                               arg5: *mut ALint64SOFT)>;
pub type LPALGETSOURCEI64VSOFT =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum,
                                               arg3: *mut ALint64SOFT)>;
pub type LPALDEFERUPDATESSOFT =
    ::std::option::Option<extern "C" fn() -> ALvoid>;
pub type LPALPROCESSUPDATESSOFT =
    ::std::option::Option<extern "C" fn() -> ALvoid>;
pub type LPALCDEVICEPAUSESOFT =
    ::std::option::Option<unsafe extern "C" fn(device: *mut ALCdevice)>;
pub type LPALCDEVICERESUMESOFT =
    ::std::option::Option<unsafe extern "C" fn(device: *mut ALCdevice)>;
pub type LPALCGETSTRINGISOFT =
    ::std::option::Option<unsafe extern "C" fn(device: *mut ALCdevice,
                                               paramName: ALCenum,
                                               index: ALCsizei)
                              -> *const ALCchar>;
pub type LPALCRESETDEVICESOFT =
    ::std::option::Option<unsafe extern "C" fn(device: *mut ALCdevice,
                                               attribs: *const ALCint)
                              -> ALCboolean>;
